<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>GamepadSaber</AssemblyName>
    <RootNamespace>GamepadSaber</RootNamespace>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="HarmonyLib" Version="2.2.2" />
  </ItemGroup>
</Project>
